import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers/Providers";
import { Navbar } from "@/components/shared/navbar/Navbar";
import { FundRaiseContextProvider } from "@/lib/context/FundraiseContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Providers>
        <FundRaiseContextProvider>
        <Navbar />
          {children}
          {/* <Toaster /> */}
        </FundRaiseContextProvider>
        </Providers>
      </body>
    </html>
  );
}
